// Code generated by MockGen. DO NOT EDIT.
// Source: internal/worker/processor.go
//
// Generated by this command:
//
//	mockgen -source=internal/worker/processor.go -destination=internal/worker/mock/mock_processor.go -package=mock RateLimiter,WebhookSender
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRateLimiter is a mock of RateLimiter interface.
type MockRateLimiter struct {
	ctrl     *gomock.Controller
	recorder *MockRateLimiterMockRecorder
	isgomock struct{}
}

// MockRateLimiterMockRecorder is the mock recorder for MockRateLimiter.
type MockRateLimiterMockRecorder struct {
	mock *MockRateLimiter
}

// NewMockRateLimiter creates a new mock instance.
func NewMockRateLimiter(ctrl *gomock.Controller) *MockRateLimiter {
	mock := &MockRateLimiter{ctrl: ctrl}
	mock.recorder = &MockRateLimiterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRateLimiter) EXPECT() *MockRateLimiterMockRecorder {
	return m.recorder
}

// Allow mocks base method.
func (m *MockRateLimiter) Allow(ctx context.Context, channel string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Allow", ctx, channel)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Allow indicates an expected call of Allow.
func (mr *MockRateLimiterMockRecorder) Allow(ctx, channel any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Allow", reflect.TypeOf((*MockRateLimiter)(nil).Allow), ctx, channel)
}

// MockWebhookSender is a mock of WebhookSender interface.
type MockWebhookSender struct {
	ctrl     *gomock.Controller
	recorder *MockWebhookSenderMockRecorder
	isgomock struct{}
}

// MockWebhookSenderMockRecorder is the mock recorder for MockWebhookSender.
type MockWebhookSenderMockRecorder struct {
	mock *MockWebhookSender
}

// NewMockWebhookSender creates a new mock instance.
func NewMockWebhookSender(ctrl *gomock.Controller) *MockWebhookSender {
	mock := &MockWebhookSender{ctrl: ctrl}
	mock.recorder = &MockWebhookSenderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWebhookSender) EXPECT() *MockWebhookSenderMockRecorder {
	return m.recorder
}

// Send mocks base method.
func (m *MockWebhookSender) Send(ctx context.Context, recipient, channel, content string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", ctx, recipient, channel, content)
	ret0, _ := ret[0].(error)
	return ret0
}

// Send indicates an expected call of Send.
func (mr *MockWebhookSenderMockRecorder) Send(ctx, recipient, channel, content any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockWebhookSender)(nil).Send), ctx, recipient, channel, content)
}
